spring:
  datasource:
    url: jdbc:mysql://localhost:${MYSQL_PORT:3306}/${MYSQL_DATABASE:article}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:article_service}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: false

cookie:
  access-token-name: ACCESS_TOKEN
  refresh-token-name: REFRESH_TOKEN
  path: /
  domain: localhost
  secure: false
  http-only: true
  same-site: Strict

jwt:
  private-key-path: classpath:keys/jwtRS256.key
  public-key-path: classpath:keys/jwtRS256.key.pub
  access-expire-minutes: 60m     # 1시간
  refresh-expire-days: 7d        # 7일

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
