version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: article_mysql_8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    command:
      # UTF-8 및 타임존 설정
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-time-zone=Asia/Seoul
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge
